import Head from "next/head";
import Script from "next/script";

const HtmlHead = () => {
  return (
    <>
      <Head>
        <title>Blink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Blink_app-icon.png" />
      </Head>
      <Script
        async
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GA_TRACKING_CODE}`}
      ></Script>
      <Script
        id="script-tag"
        dangerouslySetInnerHTML={{
          __html: `
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', ${process.env.GA_TRACKING_CODE});`,
        }}
      />
    </>
  );
};

export default HtmlHead;
